version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    working_dir: /app/se-success-web
    volumes:
      - ./:/app:cached
      - pnpm_store:/pnpm-store
      - web_nm:/app/se-success-web/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - PNPM_STORE_DIR=/pnpm-store   # ← ここを修正
    tty: true
    stdin_open: true

volumes:
  pnpm_store:
  web_nm:
